### ISSUE TITLE
Constrain10, Constrain100 on included graph results?

### ISSUE THREAD

**Issue by Steeles216000** [PapstJL4U/fgMetagame#5]
What are these constraints and how can i edit them? Python noob but i wanted to use this program for analysis.

**Comment by PapstJL4U** [comment]
To be honest, I am not 100% what the constraint does, but in a short discussion with another user I believe it comes down to sample-size for the "rock-paper-scissor" solution.

in the main method: 
>[Line 138]allWinRates = getAllWinRates(matchupPayoffs, constrain)

with
>[Line 85]getAllWinRates(matrix,division=10)

and 
>[Line 66]getWinRates(rowname,matrix,division=10)

Where division is constrain. I think constrain was not a good name choice from me. It all comes done to 
>[Line 82] probs = np.linspace(0,1,division+1)

source: https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

aka division of 10 means 11 evenly spaced samples between 0 and 1: so 0, 0.1, 0.2, 0.3, 0.4, 0.5 ...1, while a division of 100 means 101: 0, 0.01, 0.02, 0.03, .....0.1, 0.11,....1. As you might have seen, the character's win rate is a lot more detailed with higher division and can even change placement.


Because the division changes so much I put out different graphs as I am not sure, what exact impact they have. If you are more on the math site, the OG guy can be found here: https://twitter.com/Blinkity
